deploy:
  revealmd:
    build:
      target: BUILD-2023.04.05.05.51
      stg: BUILD-2023.04.05.05.51
      can: BUILD-2023.04.04.22.21
      prd: BUILD-2023.04.03.12.43
  landing:
    build:
      target: BUILD-2023.04.05.02.46
      stg: BUILD-2023.04.05.02.46
      can: BUILD-2023.04.04.22.48
      prd: x
repositories:
  solutions:
    revealmd: dr3dr3/devops-demo
    landing: dr3dr3/ss-landing
  core:
    pipeline: dr3dr3/ss-pipeline
    gitops: dr3dr3/ss-gitops
  deployment:
    stage: dr3dr3/devops-demo-stg
    canary: dr3dr3/devops-demo-can
    production: dr3dr3/devops-demo-prd
