name: REPOSITORY-VARIABLES
run-name: Set / validate configured variables in GitHub repositories

on:
  push:
    branches:
      - main
    paths:
      - repositories.yml

jobs:
  repo-variables:
    name: Set / Validate Repository Variables
    uses: dr3dr3/ss-pipeline/.github/workflows/repository-variables.yml@main
    with:
      repo-gitops: ${{ github.repository }}
    secrets: inherit